name: Deploy to GCP

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [tinacms-update]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: false
        
    - name: Install Jekyll and dependencies
      run: |
        echo "Installing Jekyll with deployment dependencies..."
        BUNDLE_GEMFILE=Gemfile.deploy bundle install --jobs 4 --retry 3
        
    - name: Build Jekyll site
      run: |
        echo "Building Jekyll site for production..."
        BUNDLE_GEMFILE=Gemfile.deploy bundle exec jekyll build --verbose
        
    - name: Verify build
      run: |
        echo "Checking build output..."
        ls -la _site/
        echo "Total files built: $(find _site -type f | wc -l)"
        
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        
    - name: Setup Google Cloud SDK  
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: dmisblogging-prod
        
    - name: Deploy to GCS
      run: |
        echo "Deploying to Google Cloud Storage..."
        gsutil -m rsync -r -d _site/ gs://blog.itsdanmanole.com/
        
        echo "Setting content types..."
        gsutil -m setmeta -h "Content-Type:text/html" -h "Cache-Control:public, max-age=3600" gs://blog.itsdanmanole.com/**/*.html
        gsutil -m setmeta -h "Content-Type:text/css" -h "Cache-Control:public, max-age=86400" gs://blog.itsdanmanole.com/**/*.css  
        gsutil -m setmeta -h "Content-Type:application/javascript" -h "Cache-Control:public, max-age=86400" gs://blog.itsdanmanole.com/**/*.js
        
        echo "Invalidating CDN cache..."
        gcloud compute url-maps invalidate-cdn-cache blog-lb --path="/*" --async
        
        echo "✅ Deployment completed successfully!"