name: Nuclear Jekyll Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Remove any cached Ruby/Bundler
      run: |
        sudo rm -rf /opt/hostedtoolcache/Ruby || true
        sudo rm -rf ~/.bundle || true
        sudo rm -rf vendor/bundle || true
    
    - name: Install Ruby 3.2 manually
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby3.2 ruby3.2-dev build-essential
        sudo gem install bundler --version 2.4.22
        ruby --version
        bundler --version
        
    - name: Install dependencies with specific bundler
      run: |
        export PATH="/usr/bin:$PATH"
        bundle config set --local path 'vendor/bundle'
        bundle install
        
    - name: Build site
      run: bundle exec jekyll build
      
    - name: Deploy to GCS
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: dmisblogging-prod
        
    - name: Sync to bucket
      run: |
        gcloud storage rsync _site/ gs://blog.itsdanmanole.com/ --recursive --delete-unmatched-destination-objects
        
    - name: Invalidate CDN
      run: |
        gcloud compute url-maps invalidate-cdn-cache blog-lb --path="/*" --async